name: Build and Deploy

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set BASE_URL environment variable
      run: echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV